import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { extractProducts } from "./seo-routes.mjs";

/* Mirrors product prices out of src/components/data/products.jsx into a plain
 * module that api/pay.js can import.
 *
 * Two reasons this exists rather than the payment endpoint reading the catalogue
 * directly: products.jsx is a React module full of JSX, which a serverless
 * function can't import, and the price has to be decided on the server. The
 * amount the browser renders is display only — charging what it sends would let
 * anyone pay $1 for a $1,350 treatment. */

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "api/_prices.js");

const priced = [];
const skipped = [];

for (const p of extractProducts({ includeHidden: true })) {
  const amount = Number(String(p.price ?? "").replace(/[^0-9.]/g, ""));
  if (!Number.isFinite(amount) || amount <= 0) {
    skipped.push(p.id);
    continue;
  }
  // Rounded to cents here so the endpoint never has to think about floats.
  priced.push([p.id, Math.round(amount * 100) / 100, p.name]);
}

if (!priced.length) {
  throw new Error("generate-prices: no priced products found in products.jsx — is the parser out of sync?");
}

const body = priced
  .sort((a, b) => a[0] - b[0])
  .map(([id, amount, name]) => `  ${id}: { amount: ${amount.toFixed(2)}, name: ${JSON.stringify(name)} },`)
  .join("\n");

writeFileSync(
  out,
  `/* GENERATED by scripts/generate-prices.mjs — do not edit by hand.
 *
 * Regenerated on every build from src/components/data/products.jsx, so a price
 * change in the catalogue can't drift from what the card is actually charged.
 * Keyed by product id, which is what /intake carries in its ?pid= param. */
export const PRICES = {
${body}
};
`,
  "utf8"
);

console.log(
  `generate-prices: wrote ${priced.length} prices to api/_prices.js` +
    (skipped.length ? ` (skipped ${skipped.length} with no price: ${skipped.join(", ")})` : "")
);
