import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { extractProducts } from "./seo-routes.mjs";

/* Mirrors product prices out of src/components/data/products.jsx into a plain
 * module that api/pay.js can import.
 *
 * Two reasons this exists rather than the payment endpoint reading the catalogue
 * directly: products.jsx is a React module full of JSX, which a serverless
 * function can't import, and the price has to be decided on the server. The
 * amount the browser renders is display only — charging what it sends would let
 * anyone pay $1 for a $1,350 treatment. */

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "api/_prices.js");

const priced = [];
const skipped = [];

for (const p of extractProducts({ includeHidden: true })) {
  const amount = Number(String(p.price ?? "").replace(/[^0-9.]/g, ""));
  if (!Number.isFinite(amount) || amount <= 0) {
    skipped.push(p.id);
    continue;
  }
  // Rounded to cents here so the endpoint never has to think about floats.
  priced.push({
    id: p.id,
    amount: Math.round(amount * 100) / 100,
    name: p.name,
    /* So the server can name a card the same way the browser does, which is
       "{category} - {product}". A later month of a plan opens its visit from
       the portal, where no page has the catalogue to hand. */
    categoryName: p.categoryName || "",
    questionnaireId: p.questionnaireId || "",
    nextRung: p.nextRung || null,
  });
}

if (!priced.length) {
  throw new Error("generate-prices: no priced products found in products.jsx — is the parser out of sync?");
}

const byId = new Map(priced.map((p) => [p.id, p]));
for (const p of priced) {
  /* A rung pointing at a product that isn't priced would send a prepaid month
     to a questionnaire nothing can charge for, so it fails the build rather
     than shipping. */
  if (p.nextRung && !byId.has(p.nextRung)) {
    throw new Error(
      `generate-prices: product ${p.id} has nextRung ${p.nextRung}, which is not a priced product`
    );
  }
  if (p.nextRung && !byId.get(p.nextRung).questionnaireId) {
    throw new Error(
      `generate-prices: product ${p.id} points at rung ${p.nextRung}, which has no questionnaireId`
    );
  }
}

const body = priced
  .sort((a, b) => a.id - b.id)
  .map(
    (p) =>
      `  ${p.id}: { amount: ${p.amount.toFixed(2)}, name: ${JSON.stringify(p.name)}` +
      `, categoryName: ${JSON.stringify(p.categoryName)}` +
      `, questionnaireId: ${JSON.stringify(p.questionnaireId)}` +
      (p.nextRung ? `, nextRung: ${p.nextRung}` : "") +
      ` },`
  )
  .join("\n");

writeFileSync(
  out,
  `/* GENERATED by scripts/generate-prices.mjs — do not edit by hand.
 *
 * Regenerated on every build from src/components/data/products.jsx, so a price
 * change in the catalogue can't drift from what the card is actually charged.
 * Keyed by product id, which is what /intake carries in its ?pid= param.
 *
 * questionnaireId and nextRung ride along because a multi-month plan has to
 * decide on the SERVER which questionnaire a prepaid month opens: a prepaid
 * fill costs nothing, so a browser allowed to name the product could turn a
 * cheap plan into free months of an expensive one. A product with no nextRung
 * repeats itself. */
export const PRICES = {
${body}
};
`,
  "utf8"
);

console.log(
  `generate-prices: wrote ${priced.length} prices to api/_prices.js` +
    (skipped.length ? ` (skipped ${skipped.length} with no price: ${skipped.join(", ")})` : "")
);
