/* GENERATED by scripts/generate-prices.mjs — do not edit by hand.
 *
 * Regenerated on every build from src/components/data/products.jsx, so a price
 * change in the catalogue can't drift from what the card is actually charged.
 * Keyed by product id, which is what /intake carries in its ?pid= param.
 *
 * questionnaireId and nextRung ride along because a multi-month plan has to
 * decide on the SERVER which questionnaire a prepaid month opens: a prepaid
 * fill costs nothing, so a browser allowed to name the product could turn a
 * cheap plan into free months of an expensive one. A product with no nextRung
 * repeats itself. */
export const PRICES = {
  1: { amount: 169.00, name: "Semaglutide/Cyanocobalamin (B12) — Starter", categoryName: "Weight Loss", questionnaireId: "df9d89e6-db14-4b17-8c34-a178b75c8f95", nextRung: 2 },
  2: { amount: 169.00, name: "Semaglutide/Cyanocobalamin (B12) — Maintenance", categoryName: "Weight Loss", questionnaireId: "b8583d31-6f0b-4c2b-9462-0c7544bc7934" },
  3: { amount: 169.00, name: "Semaglutide/Glycine Injection — Starter", categoryName: "Weight Loss", questionnaireId: "d35b721b-1a34-4894-b3e0-64f2dcd3053c" },
  4: { amount: 169.00, name: "Semaglutide/Glycine Injection — Maintenance", categoryName: "Weight Loss", questionnaireId: "b655c9c5-c6e7-4cb7-8bf0-2d37dc3609a5" },
  5: { amount: 179.00, name: "Tirzepatide/Niacinamide — Starter", categoryName: "Weight Loss", questionnaireId: "7ec64059-bbff-4448-a48a-39278f111bfa", nextRung: 6 },
  6: { amount: 199.00, name: "Tirzepatide/Niacinamide — Mid-Dose", categoryName: "Weight Loss", questionnaireId: "71ceae4f-b7b1-4788-9556-52e32ba02b7e", nextRung: 7 },
  7: { amount: 229.00, name: "Tirzepatide/Niacinamide — Maintenance", categoryName: "Weight Loss", questionnaireId: "71ceae4f-b7b1-4788-9556-52e32ba02b7e" },
  8: { amount: 179.00, name: "Tirzepatide/Glycine — Starter", categoryName: "Weight Loss", questionnaireId: "98f2af82-a1a8-4aad-98a9-730e9040fcf1" },
  9: { amount: 199.00, name: "Tirzepatide/Glycine — Mid-Dose", categoryName: "Weight Loss", questionnaireId: "d61cbcb1-f9a9-4407-87b3-c4148a9c21fe" },
  10: { amount: 229.00, name: "Tirzepatide/Glycine — Maintenance", categoryName: "Weight Loss", questionnaireId: "d61cbcb1-f9a9-4407-87b3-c4148a9c21fe" },
  11: { amount: 129.00, name: "Sermorelin Nasal Spray", categoryName: "Longevity", questionnaireId: "89a610eb-569e-4db6-9f12-3173bf7c553c" },
  12: { amount: 150.00, name: "Lipo-C Injection", categoryName: "Recovery & Wellness", questionnaireId: "79c1e11a-ffd0-4dbb-8193-4dc8685510da" },
  13: { amount: 169.00, name: "Semaglutide Sublingual Drops (SubMagna®) — Starter", categoryName: "Weight Loss", questionnaireId: "268d77e8-6ffe-4df1-9164-04e4b7d09e0f" },
  14: { amount: 279.00, name: "Semaglutide Sublingual Drops (SubMagna®) — Mid-Dose", categoryName: "Weight Loss", questionnaireId: "92eccddb-5040-4f9a-8714-fadaf80b9167" },
  15: { amount: 379.00, name: "Semaglutide Sublingual Drops (SubMagna®) — Maintenance", categoryName: "Weight Loss", questionnaireId: "92eccddb-5040-4f9a-8714-fadaf80b9167" },
  16: { amount: 139.00, name: "NAD+ Injection", categoryName: "Longevity", questionnaireId: "ae4ca1f7-e6d1-4710-bf33-9b53d5326667" },
  17: { amount: 119.00, name: "Glutathione Injection", categoryName: "Recovery & Wellness", questionnaireId: "247c0a3c-f6bc-43ec-a01b-8dd400257a7c" },
  18: { amount: 129.00, name: "NAD+ Injection — Starter", categoryName: "Longevity", questionnaireId: "ae4ca1f7-e6d1-4710-bf33-9b53d5326667" },
  19: { amount: 129.00, name: "NAD+ Injection — Mid-Dose", categoryName: "Longevity", questionnaireId: "1e74716c-356b-4680-a026-1245bdce42b6" },
  20: { amount: 179.00, name: "NAD+ Injection — Maintenance", categoryName: "Longevity", questionnaireId: "1e74716c-356b-4680-a026-1245bdce42b6" },
  23: { amount: 149.00, name: "NAD+ Sublingual Tablet", categoryName: "Longevity", questionnaireId: "91480561-864e-4bda-8bad-694696ac2e1f" },
  24: { amount: 119.00, name: "Sermorelin Injection", categoryName: "Longevity", questionnaireId: "89a610eb-569e-4db6-9f12-3173bf7c553c" },
  25: { amount: 119.00, name: "Sermorelin Mini Troche", categoryName: "Longevity", questionnaireId: "89a610eb-569e-4db6-9f12-3173bf7c553c" },
  26: { amount: 39.00, name: "Low-Dose Naltrexone (LDN) — Starter", categoryName: "Recovery & Wellness", questionnaireId: "c5535eaa-f54c-4be1-a613-323122cd275f" },
  27: { amount: 39.00, name: "Low-Dose Naltrexone (LDN) — Mid-Dose", categoryName: "Recovery & Wellness", questionnaireId: "c5535eaa-f54c-4be1-a613-323122cd275f" },
  28: { amount: 109.00, name: "Low-Dose Naltrexone (LDN) — Maintenance", categoryName: "Recovery & Wellness", questionnaireId: "c5535eaa-f54c-4be1-a613-323122cd275f" },
  29: { amount: 129.00, name: "Luminance Brightening Cream", categoryName: "Skin Health", questionnaireId: "64b181e7-0e25-4fe6-9bc5-00090a20410e" },
  30: { amount: 79.00, name: "Olympus", categoryName: "Sexual Health", questionnaireId: "" },
  31: { amount: 79.00, name: "Olympus +", categoryName: "Sexual Health", questionnaireId: "" },
  32: { amount: 79.00, name: "Olympus Peak", categoryName: "Sexual Health", questionnaireId: "9331ef1f-f9bc-4ef9-bc77-be5f02c428cf" },
  33: { amount: 109.00, name: "Olympus Max", categoryName: "Sexual Health", questionnaireId: "" },
  34: { amount: 109.00, name: "Olympus Max Peak", categoryName: "Sexual Health", questionnaireId: "" },
  35: { amount: 89.00, name: "Euphoria Cream O", categoryName: "Sexual Health", questionnaireId: "" },
  36: { amount: 79.00, name: "Euphoria Cream S", categoryName: "Sexual Health", questionnaireId: "" },
  37: { amount: 179.00, name: "Bremelanotide Injection", categoryName: "Sexual Health", questionnaireId: "77fef9b3-aa56-4dc6-ac4d-4dc3c04da262" },
  38: { amount: 69.00, name: "Bremelanotide Mini Troche", categoryName: "Sexual Health", questionnaireId: "f99bcee9-db6f-449a-81fa-34d842a4a834" },
  39: { amount: 149.00, name: "Bremelanotide Nasal Spray", categoryName: "Sexual Health", questionnaireId: "496b14b5-15c3-4e63-94ea-b063c3729976" },
  40: { amount: 1150.00, name: "Mounjaro (Tirzepatide)", categoryName: "Weight Loss", questionnaireId: "7ec64059-bbff-4448-a48a-39278f111bfa" },
  41: { amount: 1050.00, name: "Ozempic (Semaglutide)", categoryName: "Weight Loss", questionnaireId: "df9d89e6-db14-4b17-8c34-a178b75c8f95" },
  42: { amount: 1100.00, name: "Zepbound (Tirzepatide)", categoryName: "Weight Loss", questionnaireId: "7ec64059-bbff-4448-a48a-39278f111bfa" },
  43: { amount: 1350.00, name: "Wegovy (Semaglutide)", categoryName: "Weight Loss", questionnaireId: "df9d89e6-db14-4b17-8c34-a178b75c8f95" },
  44: { amount: 149.00, name: "Euphoria Cream O", categoryName: "Sexual Health", questionnaireId: "5fee7423-e1c3-4a4d-89da-2f2ccef6153f" },
  102: { amount: 165.00, name: "KPV (Lysine-Proline-Valine Peptide)", categoryName: "Supplements", questionnaireId: "b7f82b01-d377-47df-b815-4d8d7c3b710e" },
  103: { amount: 285.00, name: "Dihexa", categoryName: "Supplements", questionnaireId: "60e63139-c0fd-4ebf-b4ae-ec805dc87621" },
  104: { amount: 155.00, name: "Selank", categoryName: "Supplements", questionnaireId: "1cdda54b-3185-4ac7-b88f-177f0037a190" },
  105: { amount: 155.00, name: "Semax", categoryName: "Supplements", questionnaireId: "a6ea2b87-99fb-46b0-ae7b-da9228bb5282" },
  106: { amount: 185.00, name: "Semax / Selank 50:50 Combination", categoryName: "Supplements", questionnaireId: "1cddfacf-309c-42f7-93b8-9103e5afe7d3" },
  301: { amount: 125.95, name: "Glutaryl — Topical Glutathione Spray", categoryName: "Supplements", questionnaireId: "" },
  302: { amount: 159.00, name: "Copper Tri-Peptide — Pro-Collagen Plumping Serum", categoryName: "Skin Health", questionnaireId: "" },
};
